export default `/* Getting Started: let AI generate SQL for you.
   Type "-- + your instruction" and press "ENTER", to start AI journey with sample data of github events.
   Review the SQL generated by AI, and accept it by press "Tab" or reject it by press "Esc". */
use sample_data;
/* Try typing this instruction and press "ENTER": 
   -- Find the most popular repo from github events */

/* To experience AI-generated SQL on your own dataset, please accept Privacy terms at first. 
   PingCAP values your data privacy as top priority.*/ 
/* DISCLAIMER:
   The AI model may occasionally generate inaccurate SQL statement due to limitations of AI model.
   You can edit the AI generated SQL statement as you like. */`

export const preTips = `/* Enter "USE {database};" to start exploring your data.`
export const affixTips = `   Type "-- your instruction" followed by the Enter key to try out AI-generated SQL queries.*/`
export const newFileContent = `${preTips}\n${affixTips}\nUSE `
