/**
 * DO NOT EDIT THIS FILE, THE CONTENT IS AUTO-GENERATED
 * RUN `yarn gen:icon` TO RE-GENERATE
 */
import { ReactComponent as AiExplore01 } from './AiExplore01.svg'
import { ReactComponent as AlertCircle } from './AlertCircle.svg'
import { ReactComponent as ArrowLeft } from './ArrowLeft.svg'
import { ReactComponent as ArrowRight } from './ArrowRight.svg'
import { ReactComponent as Atom01 } from './Atom01.svg'
import { ReactComponent as BarChart07 } from './BarChart07.svg'
import { ReactComponent as BookOpen02 } from './BookOpen02.svg'
import { ReactComponent as Brackets } from './Brackets.svg'
import { ReactComponent as Building05 } from './Building05.svg'
import { ReactComponent as Calendar } from './Calendar.svg'
import { ReactComponent as Check } from './Check.svg'
import { ReactComponent as CheckCircle } from './CheckCircle.svg'
import { ReactComponent as CheckCirclebroken } from './CheckCirclebroken.svg'
import { ReactComponent as ChevronDown } from './ChevronDown.svg'
import { ReactComponent as ChevronLeft } from './ChevronLeft.svg'
import { ReactComponent as ChevronRight } from './ChevronRight.svg'
import { ReactComponent as ChevronUp } from './ChevronUp.svg'
import { ReactComponent as CodeBrowser } from './CodeBrowser.svg'
import { ReactComponent as CodeCircle02 } from './CodeCircle02.svg'
import { ReactComponent as CodeCircle03 } from './CodeCircle03.svg'
import { ReactComponent as Connect } from './Connect.svg'
import { ReactComponent as CurrencyDollarCircle } from './CurrencyDollarCircle.svg'
import { ReactComponent as Database } from './Database.svg'
import { ReactComponent as Database01 } from './Database01.svg'
import { ReactComponent as DatabseTable } from './DatabseTable.svg'
import { ReactComponent as Dataflow03 } from './Dataflow03.svg'
import { ReactComponent as DotsHorizontal } from './DotsHorizontal.svg'
import { ReactComponent as Download01 } from './Download01.svg'
import { ReactComponent as DragIn } from './DragIn.svg'
import { ReactComponent as Edit03 } from './Edit03.svg'
import { ReactComponent as Edit05 } from './Edit05.svg'
import { ReactComponent as Eye } from './Eye.svg'
import { ReactComponent as EyeOff } from './EyeOff.svg'
import { ReactComponent as FaceNeutral } from './FaceNeutral.svg'
import { ReactComponent as File06 } from './File06.svg'
import { ReactComponent as FileImport02 } from './FileImport02.svg'
import { ReactComponent as FilterFunnel01 } from './FilterFunnel01.svg'
import { ReactComponent as Glasses01 } from './Glasses01.svg'
import { ReactComponent as HelpCircle } from './HelpCircle.svg'
import { ReactComponent as HomeLine } from './HomeLine.svg'
import { ReactComponent as Inbox01 } from './Inbox01.svg'
import { ReactComponent as Key02 } from './Key02.svg'
import { ReactComponent as LaygroundGrid02 } from './LaygroundGrid02.svg'
import { ReactComponent as LayoutAlt03 } from './LayoutAlt03.svg'
import { ReactComponent as LeftIndent01 } from './LeftIndent01.svg'
import { ReactComponent as List } from './List.svg'
import { ReactComponent as LockUnlocked01 } from './LockUnlocked01.svg'
import { ReactComponent as LogOut03 } from './LogOut03.svg'
import { ReactComponent as MediaGithub } from './MediaGithub.svg'
import { ReactComponent as MediaGoogle } from './MediaGoogle.svg'
import { ReactComponent as MediaMicrosoft } from './MediaMicrosoft.svg'
import { ReactComponent as MessageChatSquare } from './MessageChatSquare.svg'
import { ReactComponent as MessageTextSquare01 } from './MessageTextSquare01.svg'
import { ReactComponent as MessageTextSquare02 } from './MessageTextSquare02.svg'
import { ReactComponent as Numberic } from './Numberic.svg'
import { ReactComponent as OpenAi } from './OpenAi.svg'
import { ReactComponent as ParagraphSpacing } from './ParagraphSpacing.svg'
import { ReactComponent as PauseCircle } from './PauseCircle.svg'
import { ReactComponent as PieChart03 } from './PieChart03.svg'
import { ReactComponent as PlayCircle } from './PlayCircle.svg'
import { ReactComponent as Plus } from './Plus.svg'
import { ReactComponent as PlusSquare } from './PlusSquare.svg'
import { ReactComponent as RefreshCw02 } from './RefreshCw02.svg'
import { ReactComponent as RefreshCw04 } from './RefreshCw04.svg'
import { ReactComponent as Repeat04 } from './Repeat04.svg'
import { ReactComponent as Right } from './Right.svg'
import { ReactComponent as RightIndent01 } from './RightIndent01.svg'
import { ReactComponent as Run } from './Run.svg'
import { ReactComponent as RunFill } from './RunFill.svg'
import { ReactComponent as Scale02 } from './Scale02.svg'
import { ReactComponent as Scale03 } from './Scale03.svg'
import { ReactComponent as SearchLg } from './SearchLg.svg'
import { ReactComponent as Server02 } from './Server02.svg'
import { ReactComponent as Settings01 } from './Settings01.svg'
import { ReactComponent as Settings02 } from './Settings02.svg'
import { ReactComponent as Shield03 } from './Shield03.svg'
import { ReactComponent as ShieldTick } from './ShieldTick.svg'
import { ReactComponent as String01 } from './String01.svg'
import { ReactComponent as SwitchHorizontal02 } from './SwitchHorizontal02.svg'
import { ReactComponent as SystemDatabase } from './SystemDatabase.svg'
import { ReactComponent as Tools } from './Tools.svg'
import { ReactComponent as Trash01 } from './Trash01.svg'
import { ReactComponent as Types02 } from './Types02.svg'
import { ReactComponent as UploadCloud01 } from './UploadCloud01.svg'
import { ReactComponent as UserCircle } from './UserCircle.svg'
import { ReactComponent as Users01 } from './Users01.svg'
import { ReactComponent as Variable } from './Variable.svg'
import { ReactComponent as XCircle } from './XCircle.svg'
import { ReactComponent as XClose } from './XClose.svg'

export const ICON_MAP = {
  AiExplore01,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Atom01,
  BarChart07,
  BookOpen02,
  Brackets,
  Building05,
  Calendar,
  Check,
  CheckCircle,
  CheckCirclebroken,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CodeBrowser,
  CodeCircle02,
  CodeCircle03,
  Connect,
  CurrencyDollarCircle,
  Database,
  Database01,
  DatabseTable,
  Dataflow03,
  DotsHorizontal,
  Download01,
  DragIn,
  Edit03,
  Edit05,
  Eye,
  EyeOff,
  FaceNeutral,
  File06,
  FileImport02,
  FilterFunnel01,
  Glasses01,
  HelpCircle,
  HomeLine,
  Inbox01,
  Key02,
  LaygroundGrid02,
  LayoutAlt03,
  LeftIndent01,
  List,
  LockUnlocked01,
  LogOut03,
  MediaGithub,
  MediaGoogle,
  MediaMicrosoft,
  MessageChatSquare,
  MessageTextSquare01,
  MessageTextSquare02,
  Numberic,
  OpenAi,
  ParagraphSpacing,
  PauseCircle,
  PieChart03,
  PlayCircle,
  Plus,
  PlusSquare,
  RefreshCw02,
  RefreshCw04,
  Repeat04,
  Right,
  RightIndent01,
  Run,
  RunFill,
  Scale02,
  Scale03,
  SearchLg,
  Server02,
  Settings01,
  Settings02,
  Shield03,
  ShieldTick,
  String01,
  SwitchHorizontal02,
  SystemDatabase,
  Tools,
  Trash01,
  Types02,
  UploadCloud01,
  UserCircle,
  Users01,
  Variable,
  XCircle,
  XClose
}

export {
  AiExplore01,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Atom01,
  BarChart07,
  BookOpen02,
  Brackets,
  Building05,
  Calendar,
  Check,
  CheckCircle,
  CheckCirclebroken,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CodeBrowser,
  CodeCircle02,
  CodeCircle03,
  Connect,
  CurrencyDollarCircle,
  Database,
  Database01,
  DatabseTable,
  Dataflow03,
  DotsHorizontal,
  Download01,
  DragIn,
  Edit03,
  Edit05,
  Eye,
  EyeOff,
  FaceNeutral,
  File06,
  FileImport02,
  FilterFunnel01,
  Glasses01,
  HelpCircle,
  HomeLine,
  Inbox01,
  Key02,
  LaygroundGrid02,
  LayoutAlt03,
  LeftIndent01,
  List,
  LockUnlocked01,
  LogOut03,
  MediaGithub,
  MediaGoogle,
  MediaMicrosoft,
  MessageChatSquare,
  MessageTextSquare01,
  MessageTextSquare02,
  Numberic,
  OpenAi,
  ParagraphSpacing,
  PauseCircle,
  PieChart03,
  PlayCircle,
  Plus,
  PlusSquare,
  RefreshCw02,
  RefreshCw04,
  Repeat04,
  Right,
  RightIndent01,
  Run,
  RunFill,
  Scale02,
  Scale03,
  SearchLg,
  Server02,
  Settings01,
  Settings02,
  Shield03,
  ShieldTick,
  String01,
  SwitchHorizontal02,
  SystemDatabase,
  Tools,
  Trash01,
  Types02,
  UploadCloud01,
  UserCircle,
  Users01,
  Variable,
  XCircle,
  XClose
}
