/**
 * DO NOT EDIT THIS FILE, THE CONTENT IS AUTO-GENERATED
 * RUN `yarn gen:icon` TO RE-GENERATE
 */
import { default as AiExplore01 } from './AiExplore01.svg'
import { default as AlertCircle } from './AlertCircle.svg'
import { default as ArrowLeft } from './ArrowLeft.svg'
import { default as ArrowRight } from './ArrowRight.svg'
import { default as Atom01 } from './Atom01.svg'
import { default as BarChart07 } from './BarChart07.svg'
import { default as BookOpen02 } from './BookOpen02.svg'
import { default as Brackets } from './Brackets.svg'
import { default as Building05 } from './Building05.svg'
import { default as Calendar } from './Calendar.svg'
import { default as Check } from './Check.svg'
import { default as CheckCircle } from './CheckCircle.svg'
import { default as CheckCirclebroken } from './CheckCirclebroken.svg'
import { default as ChevronDown } from './ChevronDown.svg'
import { default as ChevronLeft } from './ChevronLeft.svg'
import { default as ChevronRight } from './ChevronRight.svg'
import { default as ChevronUp } from './ChevronUp.svg'
import { default as CodeBrowser } from './CodeBrowser.svg'
import { default as CodeCircle02 } from './CodeCircle02.svg'
import { default as CodeCircle03 } from './CodeCircle03.svg'
import { default as Connect } from './Connect.svg'
import { default as CurrencyDollarCircle } from './CurrencyDollarCircle.svg'
import { default as Database } from './Database.svg'
import { default as Database01 } from './Database01.svg'
import { default as DatabseTable } from './DatabseTable.svg'
import { default as Dataflow03 } from './Dataflow03.svg'
import { default as DotsHorizontal } from './DotsHorizontal.svg'
import { default as Download01 } from './Download01.svg'
import { default as DragIn } from './DragIn.svg'
import { default as Edit03 } from './Edit03.svg'
import { default as Edit05 } from './Edit05.svg'
import { default as Eye } from './Eye.svg'
import { default as EyeOff } from './EyeOff.svg'
import { default as FaceNeutral } from './FaceNeutral.svg'
import { default as File06 } from './File06.svg'
import { default as FileImport02 } from './FileImport02.svg'
import { default as FilterFunnel01 } from './FilterFunnel01.svg'
import { default as Glasses01 } from './Glasses01.svg'
import { default as HelpCircle } from './HelpCircle.svg'
import { default as HomeLine } from './HomeLine.svg'
import { default as Inbox01 } from './Inbox01.svg'
import { default as Key02 } from './Key02.svg'
import { default as LaygroundGrid02 } from './LaygroundGrid02.svg'
import { default as LayoutAlt03 } from './LayoutAlt03.svg'
import { default as LeftIndent01 } from './LeftIndent01.svg'
import { default as List } from './List.svg'
import { default as LockUnlocked01 } from './LockUnlocked01.svg'
import { default as LogOut03 } from './LogOut03.svg'
import { default as MediaGithub } from './MediaGithub.svg'
import { default as MediaGoogle } from './MediaGoogle.svg'
import { default as MediaMicrosoft } from './MediaMicrosoft.svg'
import { default as MessageChatSquare } from './MessageChatSquare.svg'
import { default as MessageTextSquare01 } from './MessageTextSquare01.svg'
import { default as MessageTextSquare02 } from './MessageTextSquare02.svg'
import { default as Numberic } from './Numberic.svg'
import { default as OpenAi } from './OpenAi.svg'
import { default as ParagraphSpacing } from './ParagraphSpacing.svg'
import { default as PauseCircle } from './PauseCircle.svg'
import { default as PieChart03 } from './PieChart03.svg'
import { default as PlayCircle } from './PlayCircle.svg'
import { default as Plus } from './Plus.svg'
import { default as PlusSquare } from './PlusSquare.svg'
import { default as RefreshCw02 } from './RefreshCw02.svg'
import { default as RefreshCw04 } from './RefreshCw04.svg'
import { default as Repeat04 } from './Repeat04.svg'
import { default as Right } from './Right.svg'
import { default as RightIndent01 } from './RightIndent01.svg'
import { default as Run } from './Run.svg'
import { default as RunFill } from './RunFill.svg'
import { default as Scale02 } from './Scale02.svg'
import { default as Scale03 } from './Scale03.svg'
import { default as SearchLg } from './SearchLg.svg'
import { default as Server02 } from './Server02.svg'
import { default as Settings01 } from './Settings01.svg'
import { default as Settings02 } from './Settings02.svg'
import { default as Shield03 } from './Shield03.svg'
import { default as ShieldTick } from './ShieldTick.svg'
import { default as String01 } from './String01.svg'
import { default as SwitchHorizontal02 } from './SwitchHorizontal02.svg'
import { default as SystemDatabase } from './SystemDatabase.svg'
import { default as Tools } from './Tools.svg'
import { default as Trash01 } from './Trash01.svg'
import { default as Types02 } from './Types02.svg'
import { default as UploadCloud01 } from './UploadCloud01.svg'
import { default as UserCircle } from './UserCircle.svg'
import { default as Users01 } from './Users01.svg'
import { default as Variable } from './Variable.svg'
import { default as XCircle } from './XCircle.svg'
import { default as XClose } from './XClose.svg'

export const ICON_MAP = {
  AiExplore01,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Atom01,
  BarChart07,
  BookOpen02,
  Brackets,
  Building05,
  Calendar,
  Check,
  CheckCircle,
  CheckCirclebroken,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CodeBrowser,
  CodeCircle02,
  CodeCircle03,
  Connect,
  CurrencyDollarCircle,
  Database,
  Database01,
  DatabseTable,
  Dataflow03,
  DotsHorizontal,
  Download01,
  DragIn,
  Edit03,
  Edit05,
  Eye,
  EyeOff,
  FaceNeutral,
  File06,
  FileImport02,
  FilterFunnel01,
  Glasses01,
  HelpCircle,
  HomeLine,
  Inbox01,
  Key02,
  LaygroundGrid02,
  LayoutAlt03,
  LeftIndent01,
  List,
  LockUnlocked01,
  LogOut03,
  MediaGithub,
  MediaGoogle,
  MediaMicrosoft,
  MessageChatSquare,
  MessageTextSquare01,
  MessageTextSquare02,
  Numberic,
  OpenAi,
  ParagraphSpacing,
  PauseCircle,
  PieChart03,
  PlayCircle,
  Plus,
  PlusSquare,
  RefreshCw02,
  RefreshCw04,
  Repeat04,
  Right,
  RightIndent01,
  Run,
  RunFill,
  Scale02,
  Scale03,
  SearchLg,
  Server02,
  Settings01,
  Settings02,
  Shield03,
  ShieldTick,
  String01,
  SwitchHorizontal02,
  SystemDatabase,
  Tools,
  Trash01,
  Types02,
  UploadCloud01,
  UserCircle,
  Users01,
  Variable,
  XCircle,
  XClose
}

export {
  AiExplore01,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Atom01,
  BarChart07,
  BookOpen02,
  Brackets,
  Building05,
  Calendar,
  Check,
  CheckCircle,
  CheckCirclebroken,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CodeBrowser,
  CodeCircle02,
  CodeCircle03,
  Connect,
  CurrencyDollarCircle,
  Database,
  Database01,
  DatabseTable,
  Dataflow03,
  DotsHorizontal,
  Download01,
  DragIn,
  Edit03,
  Edit05,
  Eye,
  EyeOff,
  FaceNeutral,
  File06,
  FileImport02,
  FilterFunnel01,
  Glasses01,
  HelpCircle,
  HomeLine,
  Inbox01,
  Key02,
  LaygroundGrid02,
  LayoutAlt03,
  LeftIndent01,
  List,
  LockUnlocked01,
  LogOut03,
  MediaGithub,
  MediaGoogle,
  MediaMicrosoft,
  MessageChatSquare,
  MessageTextSquare01,
  MessageTextSquare02,
  Numberic,
  OpenAi,
  ParagraphSpacing,
  PauseCircle,
  PieChart03,
  PlayCircle,
  Plus,
  PlusSquare,
  RefreshCw02,
  RefreshCw04,
  Repeat04,
  Right,
  RightIndent01,
  Run,
  RunFill,
  Scale02,
  Scale03,
  SearchLg,
  Server02,
  Settings01,
  Settings02,
  Shield03,
  ShieldTick,
  String01,
  SwitchHorizontal02,
  SystemDatabase,
  Tools,
  Trash01,
  Types02,
  UploadCloud01,
  UserCircle,
  Users01,
  Variable,
  XCircle,
  XClose
}
