name: Lint

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - id: changed_files
        uses: trilom/file-changes-action@v1
        with:
          output: ' '
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-
      - run: yarn --frozen-lockfile --network-timeout 180000
      - run: yarn api:gen
      - run: yarn lint:ci ${{ steps.changed_files.outputs.files_added}} ${{ steps.changed_files.outputs.files_modified}}